#!/usr/bin/env bash
#Redirect

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i '43i location /redirect_me{\nrewrite ^/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n}\n' /etc/nginx/sites-available/default
sudo service nginx restart
