#!/usr/bin/env bash
#Redirect

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '43i location /redirect_me{\nrewrite ^/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4v permanent;\n}\n' /etc/nginx/sites-available/default
sudo service nginx start
