#!/usr/bin/env bash
#Redirect

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo sh -c "echo 'Holberton School' > /var/www/html/index.html"
sudo sed -i '43i location /redirect_me{\nrewrite ^/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4v permanent;\n}\n' /etc/nginx/sites-available/default
sudo echo "Ceci n'est pas une page" >> /usr/share/nginx/html/custom_404.html
custom_404="\\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "39i $custom_404" /etc/nginx/sites-enabled/default
sudo service nginx restart
