#!/usr/bin/env bash
# this script prints Holberton School ten times #
i=1
while ((i <= 100)); do
    if ((i % 3 == 0 && i % 5 == 0)); then
	echo "FizzBuzz"
	elif ((i % 3 == 0)); then
	echo "Fizz"
	elif ((i % 5 == 0)); then
	echo "Buzz"
	else
	echo $i
	fi
    ((i++))
done
