#!/usr/bin/env bash
# this script prints Holberton School ten times #
fil="/etc/passwd"
IFS=':'
while read l1 l2 l3 l4 l5 l6 l7
do
    printf "The user %s is part of the %s gang, lives in %s and rides %s. %s's place is protected by \
the passcode %s, more info about the user here: %s\n" "$l1" "$l4" "$l6" "$l7" "$l3" "$l2" "$l5"
done < $fil
