#!/usr/bin/env bash
# this script prints holberton school 10 times with while #
i="0"
while [ $i -lt 10 ]
do
	if [ $i -eq 8 ]
	then
	    echo "Holberton School"
	    echo "Hi"
	else
	    echo "Holberton School"
	fi
	i=$(( i + 1 ))
done
