#!/usr/bin/env bash
# this script prints holberton school 10 times with while #
i="0"
while [ $i -lt 10 ]
do
	if [ $i -eq 3 ]
	then
	    echo "bad luck"
	else
	    if [ $i -eq 7 ]
	    then
		echo "good luck"
	    else
	    	echo "Holberton School"
	    fi
	fi
	i=$(( i + 1 ))
done
