#!/usr/bin/env bash
# this script print 12 hours and 1 to 59 minutes #
h="0"
while [ $h -lt 13 ]
do
    m="1"
    echo "Hour:" $h
    while [ $m -lt 60 ]
    do
	echo $m
	m=$(( m + 1 ))
    done
    h=$(( h + 1))
done
