#!/usr/bin/env bash
#this script change the localhost ip and fb ip
cp /etc/hosts ~/hosts
sudo sed -i "s/127.0.0.1/127.0.0.2/" /etc/hosts
echo "8.8.8.8 facebook.com" >> ~/hosts
sudo cp -f ~/hosts /etc/hosts
