#!/usr/bin/env bash
#this script change the localhost ip and fb ip
sudo sed -i "s/127.0.0.1/127.0.0.2/" /etc/hosts
cp /etc/hosts ./hosts
echo "8.8.8.8 facebook" >> ./hosts
sudo cp -f ./hosts /etc/hosts
